name: push-workflow
on: 
  push:
    branches:
      - "main"

jobs:
  testcode:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: Set up golang environment
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - name: install dependencies
        run: go mod download
      - name: test go code
        run: go test ./...
  deploycode:
    runs-on: ubuntu-latest
    needs: testcode
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: Set up golang environment
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - name: install go dependencies
        run: go mod download
      - name: package go lambdas
        run: bash package.sh
      - name: install serverless dependencies
        run: npm ci
      - name: deploy serverless
        uses: serverless/github-action@v3.1
        with:
          args: deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
